# Site settings
title: Brice's Blog
description: Highlighting some of my more technical adventures
application_insights: bc55e726-6559-4f0c-8c4d-85be3d47ec33
author:
  name: Brice Lambson
  email: brice@bricelam.net
minima:
  social_links:
    - platform: github
      user_url: https://github.com/bricelam
    - platform: twitter
      user_url: https://twitter.com/bricelambs
    - platform: youtube
      user_url: https://www.youtube.com/channel/UCKQoPIhSjqnnq20sD9fGbeA
header_pages:
  - about.md
  - projects.md
  - tags/index.html
  - links.md
paginate: 7
paginate_path: "/page/:num/"
show_excerpts: true
future: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
