# Site settings
title: Brice's Blog
description: Highlighting some of my more technical adventures
application_insights: bc55e726-6559-4f0c-8c4d-85be3d47ec33
author:
  name: Brice Lambson
  email: brice@bricelam.net
minima:
  nav_pages:
    - about.md
    - projects.md
    - tags/index.html
    - links.md
  show_excerpts: true
  social_links:
    - title: GitHub
      icon: github
      url: https://github.com/bricelam
    - title: Bluesky
      icon: bluesky
      url: https://bsky.app/profile/bricelam.net
    - title: YouTube
      icon: youtube
      url: https://www.youtube.com/channel/UCKQoPIhSjqnnq20sD9fGbeA

paginate: 7
paginate_path: "/page/:num/"
future: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
