# Site settings
title: Brice's Blog
description: Highlighting some of my more technical adventures
disqus:
  shortname: bricelam
application_insights: bc55e726-6559-4f0c-8c4d-85be3d47ec33
author:
  name: Brice Lambson
  email: brice@bricelam.net
minima:
  social_links:
    github:  bricelam
    twitter: bricelambs
    youtube_channel: UCKQoPIhSjqnnq20sD9fGbeA
    youtube_channel_name: Brice Lambson
header_pages:
  - about.md
  - projects.md
  - tags/index.html
  - links.md
paginate: 7
paginate_path: "/page/:num/"
show_excerpts: true

# Build settings
# TODO: Revert when Minima 3.0 is released
#theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
